language: scala

before_script:
  - mkdir -p "$HOME"/.sbt/0.13/plugins/
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")' > "$HOME"/.sbt/0.13/plugins/build.sbt
  - mkdir -p "$HOME"/.sbt/1.0/plugins/
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")' > "$HOME"/.sbt/1.0/plugins/build.sbt

script:
  - sbt ^scripted

# Use container-based infrastructure (default, but just in case)
sudo: false

cache:
  directories:
    # Save a few minutes by caching dependencies
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  webhooks:
    urls:
      # Gitter notifications
      - https://webhooks.gitter.im/e/aa2f53238a675a209d64
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
